<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://server.jaxws.test.jboss.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="GreetingService" targetNamespace="http://server.jaxws.test.jboss.org/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://server.jaxws.test.jboss.org/" elementFormDefault="unqualified" targetNamespace="http://server.jaxws.test.jboss.org/" version="1.0">

  <xs:element name="greeting" type="tns:greeting"/>

  <xs:element name="greetingResponse" type="tns:greetingResponse"/>

  <xs:complexType name="greeting">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="greetingResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="greeting">
    <wsdl:part element="tns:greeting" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="greetingResponse">
    <wsdl:part element="tns:greetingResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Greeting">
    <wsdl:operation name="greeting">
      <wsdl:input message="tns:greeting" name="greeting">
    </wsdl:input>
      <wsdl:output message="tns:greetingResponse" name="greetingResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GreetingServiceSoapBinding" type="tns:Greeting">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="greeting">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="greeting">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="greetingResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GreetingService">
    <wsdl:port binding="tns:GreetingServiceSoapBinding" name="GreetingPort">
      <soap:address location="http://localhost:8080/jaxws-server/greeting"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>